name: e2e-tests
services:
  playwright-e2e:
    image: ecmchow/node-playwright-pnpm:v1.46.1-node20-pnpm9-jammy
    command: sh -c "pnpm install && pnpm e2e:internal $${UPDATE_SNAPSHOTS}"
    working_dir: /e2e
    volumes:
      - .:/e2e
      - /e2e/node_modules
      - /e2e/storybook-static
